/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface SousChefInterface extends ethers.utils.Interface {
  functions: {
    "PRECISION()": FunctionFragment;
    "burnYieldToken(address,uint256)": FunctionFragment;
    "claimSushiRewardWithBurningYieldToken(uint256,uint256)": FunctionFragment;
    "createYieldTokens(uint256[],address[])": FunctionFragment;
    "deposit(uint256,uint256)": FunctionFragment;
    "depositWithPermit(uint256,uint256,address,uint256,uint8,bytes32,bytes32)": FunctionFragment;
    "getYieldTokenAddress(uint256)": FunctionFragment;
    "masterChef()": FunctionFragment;
    "owner()": FunctionFragment;
    "pendingSushiRewardWithYieldToken(uint256,uint256)": FunctionFragment;
    "pendingYieldToken(uint256)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "rewardPoolInfo(uint256)": FunctionFragment;
    "sushi()": FunctionFragment;
    "sushiBar()": FunctionFragment;
    "sushiRewardPerYieldToken()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateStrategy(uint256,address)": FunctionFragment;
    "userInfo(uint256,address)": FunctionFragment;
    "withdraw(uint256,uint256)": FunctionFragment;
    "yTokenInfoOf(uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "PRECISION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "burnYieldToken",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimSushiRewardWithBurningYieldToken",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createYieldTokens",
    values: [BigNumberish[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositWithPermit",
    values: [
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getYieldTokenAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "masterChef",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingSushiRewardWithYieldToken",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingYieldToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardPoolInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "sushi", values?: undefined): string;
  encodeFunctionData(functionFragment: "sushiBar", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "sushiRewardPerYieldToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateStrategy",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "userInfo",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "yTokenInfoOf",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "PRECISION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "burnYieldToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimSushiRewardWithBurningYieldToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createYieldTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositWithPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getYieldTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "masterChef", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingSushiRewardWithYieldToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingYieldToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardPoolInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sushi", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sushiBar", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sushiRewardPerYieldToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userInfo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "yTokenInfoOf",
    data: BytesLike
  ): Result;

  events: {
    "Claimed(address,uint256,address)": EventFragment;
    "Deposited(address,uint256,address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "UpdateMultipleRewardStrategy(uint256,address,address,address)": EventFragment;
    "Withdrawn(address,uint256,address)": EventFragment;
    "YieldTokenCreated(uint256,address,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Claimed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Deposited"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "UpdateMultipleRewardStrategy"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdrawn"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "YieldTokenCreated"): EventFragment;
}

export type ClaimedEvent = TypedEvent<
  [string, BigNumber, string] & {
    yieldToken: string;
    amount: BigNumber;
    to: string;
  }
>;

export type DepositedEvent = TypedEvent<
  [string, BigNumber, string] & {
    yieldToken: string;
    amount: BigNumber;
    to: string;
  }
>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export type UpdateMultipleRewardStrategyEvent = TypedEvent<
  [BigNumber, string, string, string] & {
    pid: BigNumber;
    lpToken: string;
    yieldToken: string;
    strategy: string;
  }
>;

export type WithdrawnEvent = TypedEvent<
  [string, BigNumber, string] & {
    yieldToken: string;
    amount: BigNumber;
    to: string;
  }
>;

export type YieldTokenCreatedEvent = TypedEvent<
  [BigNumber, string, string, string] & {
    pid: BigNumber;
    lpToken: string;
    yieldToken: string;
    strategy: string;
  }
>;

export class SousChef extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SousChefInterface;

  functions: {
    PRECISION(overrides?: CallOverrides): Promise<[BigNumber]>;

    burnYieldToken(
      yieldToken: string,
      yieldTokenAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claimSushiRewardWithBurningYieldToken(
      pid: BigNumberish,
      yieldTokenAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createYieldTokens(
      pids: BigNumberish[],
      strategies: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deposit(
      pid: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    depositWithPermit(
      pid: BigNumberish,
      amount: BigNumberish,
      lpToken: string,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getYieldTokenAddress(
      pid: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    masterChef(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pendingSushiRewardWithYieldToken(
      pid: BigNumberish,
      yieldTokenAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { sushiReward: BigNumber }>;

    pendingYieldToken(
      pid: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { yieldTokenAmount: BigNumber }>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    rewardPoolInfo(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        accSushiPerShare: BigNumber;
        lastRewardBlock: BigNumber;
      }
    >;

    sushi(overrides?: CallOverrides): Promise<[string]>;

    sushiBar(overrides?: CallOverrides): Promise<[string]>;

    sushiRewardPerYieldToken(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { sushiReward: BigNumber }>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateStrategy(
      pid: BigNumberish,
      strategy: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    userInfo(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        userAmount: BigNumber;
        rewardDebt: BigNumber;
        xSushiRewardDebt: BigNumber;
      }
    >;

    withdraw(
      pid: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    yTokenInfoOf(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, BigNumber] & {
        lpToken: string;
        yieldToken: string;
        strategy: string;
        accXSushiPerShare: BigNumber;
      }
    >;
  };

  PRECISION(overrides?: CallOverrides): Promise<BigNumber>;

  burnYieldToken(
    yieldToken: string,
    yieldTokenAmount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claimSushiRewardWithBurningYieldToken(
    pid: BigNumberish,
    yieldTokenAmount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createYieldTokens(
    pids: BigNumberish[],
    strategies: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deposit(
    pid: BigNumberish,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  depositWithPermit(
    pid: BigNumberish,
    amount: BigNumberish,
    lpToken: string,
    deadline: BigNumberish,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getYieldTokenAddress(
    pid: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  masterChef(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  pendingSushiRewardWithYieldToken(
    pid: BigNumberish,
    yieldTokenAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  pendingYieldToken(
    pid: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  rewardPoolInfo(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      accSushiPerShare: BigNumber;
      lastRewardBlock: BigNumber;
    }
  >;

  sushi(overrides?: CallOverrides): Promise<string>;

  sushiBar(overrides?: CallOverrides): Promise<string>;

  sushiRewardPerYieldToken(overrides?: CallOverrides): Promise<BigNumber>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateStrategy(
    pid: BigNumberish,
    strategy: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  userInfo(
    arg0: BigNumberish,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      userAmount: BigNumber;
      rewardDebt: BigNumber;
      xSushiRewardDebt: BigNumber;
    }
  >;

  withdraw(
    pid: BigNumberish,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  yTokenInfoOf(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, BigNumber] & {
      lpToken: string;
      yieldToken: string;
      strategy: string;
      accXSushiPerShare: BigNumber;
    }
  >;

  callStatic: {
    PRECISION(overrides?: CallOverrides): Promise<BigNumber>;

    burnYieldToken(
      yieldToken: string,
      yieldTokenAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimSushiRewardWithBurningYieldToken(
      pid: BigNumberish,
      yieldTokenAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createYieldTokens(
      pids: BigNumberish[],
      strategies: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    deposit(
      pid: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        reward: BigNumber;
        yieldTokenReward: BigNumber;
      }
    >;

    depositWithPermit(
      pid: BigNumberish,
      amount: BigNumberish,
      lpToken: string,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getYieldTokenAddress(
      pid: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    masterChef(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    pendingSushiRewardWithYieldToken(
      pid: BigNumberish,
      yieldTokenAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pendingYieldToken(
      pid: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    rewardPoolInfo(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        accSushiPerShare: BigNumber;
        lastRewardBlock: BigNumber;
      }
    >;

    sushi(overrides?: CallOverrides): Promise<string>;

    sushiBar(overrides?: CallOverrides): Promise<string>;

    sushiRewardPerYieldToken(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateStrategy(
      pid: BigNumberish,
      strategy: string,
      overrides?: CallOverrides
    ): Promise<void>;

    userInfo(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        userAmount: BigNumber;
        rewardDebt: BigNumber;
        xSushiRewardDebt: BigNumber;
      }
    >;

    withdraw(
      pid: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        reward: BigNumber;
        yieldTokenReward: BigNumber;
      }
    >;

    yTokenInfoOf(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, BigNumber] & {
        lpToken: string;
        yieldToken: string;
        strategy: string;
        accXSushiPerShare: BigNumber;
      }
    >;
  };

  filters: {
    "Claimed(address,uint256,address)"(
      yieldToken?: string | null,
      amount?: null,
      to?: string | null
    ): TypedEventFilter<
      [string, BigNumber, string],
      { yieldToken: string; amount: BigNumber; to: string }
    >;

    Claimed(
      yieldToken?: string | null,
      amount?: null,
      to?: string | null
    ): TypedEventFilter<
      [string, BigNumber, string],
      { yieldToken: string; amount: BigNumber; to: string }
    >;

    "Deposited(address,uint256,address)"(
      yieldToken?: string | null,
      amount?: null,
      to?: string | null
    ): TypedEventFilter<
      [string, BigNumber, string],
      { yieldToken: string; amount: BigNumber; to: string }
    >;

    Deposited(
      yieldToken?: string | null,
      amount?: null,
      to?: string | null
    ): TypedEventFilter<
      [string, BigNumber, string],
      { yieldToken: string; amount: BigNumber; to: string }
    >;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    "UpdateMultipleRewardStrategy(uint256,address,address,address)"(
      pid?: BigNumberish | null,
      lpToken?: string | null,
      yieldToken?: string | null,
      strategy?: null
    ): TypedEventFilter<
      [BigNumber, string, string, string],
      { pid: BigNumber; lpToken: string; yieldToken: string; strategy: string }
    >;

    UpdateMultipleRewardStrategy(
      pid?: BigNumberish | null,
      lpToken?: string | null,
      yieldToken?: string | null,
      strategy?: null
    ): TypedEventFilter<
      [BigNumber, string, string, string],
      { pid: BigNumber; lpToken: string; yieldToken: string; strategy: string }
    >;

    "Withdrawn(address,uint256,address)"(
      yieldToken?: string | null,
      amount?: null,
      to?: string | null
    ): TypedEventFilter<
      [string, BigNumber, string],
      { yieldToken: string; amount: BigNumber; to: string }
    >;

    Withdrawn(
      yieldToken?: string | null,
      amount?: null,
      to?: string | null
    ): TypedEventFilter<
      [string, BigNumber, string],
      { yieldToken: string; amount: BigNumber; to: string }
    >;

    "YieldTokenCreated(uint256,address,address,address)"(
      pid?: BigNumberish | null,
      lpToken?: string | null,
      yieldToken?: string | null,
      strategy?: null
    ): TypedEventFilter<
      [BigNumber, string, string, string],
      { pid: BigNumber; lpToken: string; yieldToken: string; strategy: string }
    >;

    YieldTokenCreated(
      pid?: BigNumberish | null,
      lpToken?: string | null,
      yieldToken?: string | null,
      strategy?: null
    ): TypedEventFilter<
      [BigNumber, string, string, string],
      { pid: BigNumber; lpToken: string; yieldToken: string; strategy: string }
    >;
  };

  estimateGas: {
    PRECISION(overrides?: CallOverrides): Promise<BigNumber>;

    burnYieldToken(
      yieldToken: string,
      yieldTokenAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claimSushiRewardWithBurningYieldToken(
      pid: BigNumberish,
      yieldTokenAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createYieldTokens(
      pids: BigNumberish[],
      strategies: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deposit(
      pid: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    depositWithPermit(
      pid: BigNumberish,
      amount: BigNumberish,
      lpToken: string,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getYieldTokenAddress(
      pid: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    masterChef(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pendingSushiRewardWithYieldToken(
      pid: BigNumberish,
      yieldTokenAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pendingYieldToken(
      pid: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    rewardPoolInfo(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sushi(overrides?: CallOverrides): Promise<BigNumber>;

    sushiBar(overrides?: CallOverrides): Promise<BigNumber>;

    sushiRewardPerYieldToken(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateStrategy(
      pid: BigNumberish,
      strategy: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    userInfo(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdraw(
      pid: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    yTokenInfoOf(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    PRECISION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    burnYieldToken(
      yieldToken: string,
      yieldTokenAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claimSushiRewardWithBurningYieldToken(
      pid: BigNumberish,
      yieldTokenAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createYieldTokens(
      pids: BigNumberish[],
      strategies: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deposit(
      pid: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    depositWithPermit(
      pid: BigNumberish,
      amount: BigNumberish,
      lpToken: string,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getYieldTokenAddress(
      pid: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    masterChef(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pendingSushiRewardWithYieldToken(
      pid: BigNumberish,
      yieldTokenAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pendingYieldToken(
      pid: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    rewardPoolInfo(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    sushi(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sushiBar(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sushiRewardPerYieldToken(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateStrategy(
      pid: BigNumberish,
      strategy: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    userInfo(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdraw(
      pid: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    yTokenInfoOf(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
