/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IMultipleRewardStrategy,
  IMultipleRewardStrategyInterface,
} from "../IMultipleRewardStrategy";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "yieldTokenAmount",
        type: "uint256",
      },
    ],
    name: "claimReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "sousChef",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IMultipleRewardStrategy__factory {
  static readonly abi = _abi;
  static createInterface(): IMultipleRewardStrategyInterface {
    return new utils.Interface(_abi) as IMultipleRewardStrategyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMultipleRewardStrategy {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IMultipleRewardStrategy;
  }
}
